<script setup>
import { nextTick, ref } from 'vue'
import { getPosts } from '../utils/communityStorage'
const KEY='localhub-chat-v1', open=ref(false), input=ref(''), sending=ref(false), error=ref(''), listEl=ref(null)
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x.slice(-20):[]}catch{return[]}}
const messages=ref(load())
function persist(){messages.value=messages.value.slice(-20);localStorage.setItem(KEY,JSON.stringify(messages.value))}
async function context(){const [s,p,k]=await Promise.all([fetch('/data/gwangju-data-summary.json').then(r=>r.json()),fetch('/data/police_gwangju.clean.json').then(r=>r.json()),fetch('/data/safety-knowledge.json').then(r=>r.json())]);const posts=getPosts().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,10).map(({title,content,category,createdAt})=>({title,content,category,createdAt}));return `검증된 안전지식: ${JSON.stringify(k)}\n안전 통계: ${JSON.stringify(s)}\n경찰 시설: ${JSON.stringify(p.map(({name,district,type,address})=>({name,district,type,address})))}\n최신 주민 게시글(공식 정보 아님): ${JSON.stringify(posts)}`}
async function send(){const text=input.value.trim();if(!text||sending.value)return;messages.value.push({role:'user',content:text});input.value='';persist();error.value='';await nextTick();listEl.value?.scrollTo(0,listEl.value.scrollHeight);const key=import.meta.env.VITE_OPENAI_API_KEY;if(!key){messages.value.push({role:'assistant',content:'OpenAI API 키가 설정되지 않았습니다. 프로젝트의 .env에 VITE_OPENAI_API_KEY를 설정한 뒤 다시 실행해주세요.'});persist();return}sending.value=true;try{const dataContext=await context();const apiMessages=[{role:'system',content:`너는 광주 지역 안전 도우미다. 제공 데이터 밖의 사실을 만들어내지 않는다. 긴급 상황이면 112 또는 119 신고를 먼저 안내한다. 답변은 간결한 한국어로 작성한다.\n${dataContext}`},...messages.value.slice(-12)];const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5-mini',messages:apiMessages,reasoning_effort:'minimal',max_completion_tokens:500})});if(!r.ok){const failure=await r.json().catch(()=>null);if(r.status===401)throw new Error('API 키가 올바르지 않습니다.');if(r.status===429)throw new Error('요청 한도를 초과했습니다. 잠시 후 다시 시도해주세요.');throw new Error(failure?.error?.message||`AI 요청에 실패했습니다. (${r.status})`)}const data=await r.json();const answer=data.choices?.[0]?.message?.content?.trim();if(!answer)throw new Error('AI가 빈 응답을 반환했습니다.');messages.value.push({role:'assistant',content:answer});persist()}catch(e){error.value=e instanceof TypeError?'네트워크 연결을 확인해주세요.':e.message}finally{sending.value=false;await nextTick();listEl.value?.scrollTo(0,listEl.value.scrollHeight)}}
function keydown(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}
function clear(){messages.value=[];localStorage.removeItem(KEY);error.value=''}
</script>
<template><button class="floating" aria-label="안전 챗봇 열기" @click="open=!open">{{open?'×':'💬'}}<span v-if="!open">안전 도우미</span></button><section v-if="open" class="chat card" aria-label="안전 챗봇"><header><div><strong>LocalHub 안전 도우미</strong><small>지역 데이터 기반 AI 안내</small></div><button @click="open=false">×</button></header><div ref="listEl" class="messages"><div v-if="!messages.length" class="welcome"><b>무엇을 도와드릴까요?</b><p>주변 치안시설, 범죄 예방 행동, 안전 정보를 물어보세요.</p></div><div v-for="(m,i) in messages" :key="i" :class="['message',m.role]">{{m.content}}</div><div v-if="sending" class="message assistant">답변을 준비하고 있습니다…</div><p v-if="error" class="chat-error">{{error}}</p></div><footer><textarea v-model="input" rows="2" placeholder="안전 관련 질문을 입력하세요" @keydown="keydown"></textarea><button :disabled="sending||!input.trim()" @click="send">전송</button></footer><button class="clear" @click="clear">대화 지우기</button></section></template>
<style scoped>
.floating{position:fixed;right:25px;bottom:25px;z-index:210;background:var(--green);color:#fff;border-radius:999px;min-width:56px;height:56px;padding:0 18px;font-weight:850;box-shadow:0 12px 30px #0f765755;font-size:1rem}.floating span{margin-left:7px}.chat{position:fixed;right:25px;bottom:92px;width:min(390px,calc(100vw - 30px));height:570px;z-index:200;display:flex;flex-direction:column;overflow:hidden;box-shadow:0 20px 60px #0b2e2360}.chat header{display:flex;justify-content:space-between;align-items:center;background:#104f3d;color:#fff;padding:16px 18px}.chat header strong,.chat header small{display:block}.chat header small{font-size:.7rem;opacity:.72;margin-top:2px}.chat header button{background:transparent;color:#fff;font-size:1.4rem}.messages{flex:1;overflow:auto;padding:17px;background:#f4f8f6;display:flex;flex-direction:column;gap:10px}.welcome{text-align:center;margin:auto;color:var(--muted);padding:25px}.message{max-width:86%;padding:10px 12px;border-radius:13px;white-space:pre-wrap;font-size:.9rem;line-height:1.55}.message.user{align-self:flex-end;background:var(--green);color:#fff;border-bottom-right-radius:3px}.message.assistant{align-self:flex-start;background:#fff;border:1px solid var(--line);border-bottom-left-radius:3px}.chat-error{color:#a52f2f;font-size:.82rem;margin:0}.chat footer{display:flex;gap:8px;padding:12px;border-top:1px solid var(--line);background:#fff}.chat textarea{resize:none;flex:1;border:1px solid #bfd0c8;border-radius:10px;padding:9px}.chat footer button{background:var(--green);color:#fff;border-radius:9px;padding:0 13px;font-weight:800}.chat footer button:disabled{opacity:.4}.clear{background:#fff;color:var(--muted);padding:8px;font-size:.77rem;border-top:1px solid #edf2ef}@media(max-width:550px){.floating{right:15px;bottom:15px}.chat{inset:74px 10px 82px;width:auto;height:auto}.floating span{display:none}}
</style>
