<script setup>
import { computed, onMounted, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { CATEGORIES, ensureSeedPosts } from '../utils/communityStorage'
const posts=ref([]), category=ref('전체'), query=ref(''), page=ref(1), pageSize=10
onMounted(async()=>posts.value=await ensureSeedPosts())
const filtered=computed(()=>posts.value.filter(p=>(category.value==='전체'||p.category===category.value)&&(!query.value||`${p.title} ${p.content}`.toLowerCase().includes(query.value.toLowerCase()))).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))
const pages=computed(()=>Math.max(1,Math.ceil(filtered.value.length/pageSize)))
const visible=computed(()=>filtered.value.slice((page.value-1)*pageSize,page.value*pageSize))
function reset(){page.value=1}
const date=v=>new Intl.DateTimeFormat('ko-KR').format(new Date(v))
</script>
<template><main class="page"><div class="head"><div><h1 class="page-title">동네 커뮤니티</h1><p class="page-subtitle">광주 시민과 안전 정보와 동네 소식을 나눠보세요.</p></div><RouterLink class="btn" to="/community/write">글쓰기</RouterLink></div><p class="notice">게시글은 서버가 아닌 현재 브라우저에만 저장됩니다.</p><div class="toolbar card"><div class="tabs"><button v-for="item in ['전체',...CATEGORIES]" :key="item" :class="{active:category===item}" @click="category=item;reset()">{{item}}</button></div><input v-model="query" class="search-input" placeholder="제목·내용 검색" @input="reset"></div><section class="list card"><div class="list-head"><span>게시글 {{filtered.length}}개</span><small>최신순</small></div><RouterLink v-for="post in visible" :key="post.id" class="row" :to="`/community/${post.id}`"><span class="tag">{{post.category}}</span><div><strong>{{post.title}}</strong><p>{{post.content}}</p></div><small>{{date(post.createdAt)}}<br>조회 {{post.viewCount||0}}</small></RouterLink><div v-if="!visible.length" class="empty">조건에 맞는 게시글이 없습니다.</div></section><div class="pagination" v-if="pages>1"><button v-for="n in pages" :key="n" :class="{active:page===n}" @click="page=n">{{n}}</button></div></main></template>
<style scoped>
.head{display:flex;justify-content:space-between;align-items:start}.notice{margin-bottom:15px}.toolbar{padding:14px;display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:15px}.tabs{display:flex;gap:5px;flex-wrap:wrap}.tabs button,.pagination button{padding:8px 11px;border-radius:8px;background:transparent;color:var(--muted);font-weight:750}.tabs button.active,.pagination button.active{background:#e3f2eb;color:var(--green)}.search-input{max-width:260px}.list{overflow:hidden}.list-head{padding:15px 20px;background:#f9fbfa;display:flex;justify-content:space-between;color:var(--muted)}.row{display:grid;grid-template-columns:80px 1fr 110px;align-items:center;gap:15px;padding:17px 20px;border-top:1px solid #edf2ef;text-decoration:none;color:inherit}.row strong{font-size:1rem}.row p{margin:4px 0 0;color:var(--muted);font-size:.86rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:650px}.row>small{text-align:right;color:#7d8c87}.pagination{display:flex;justify-content:center;gap:5px;margin-top:20px}@media(max-width:680px){.head{align-items:center}.toolbar{align-items:stretch;flex-direction:column}.search-input{max-width:none}.row{grid-template-columns:1fr 70px}.row>.tag{grid-column:1/-1;width:max-content}.row>small{grid-column:2;grid-row:2}.row div{grid-column:1;grid-row:2}}
</style>
