<script setup>
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { deletePost, incrementView, verifyPassword } from '../utils/communityStorage'
const route=useRoute(),router=useRouter(),post=ref(null),modal=ref(''),password=ref(''),error=ref('')
onMounted(()=>post.value=incrementView(route.params.id))
function confirm(){if(!verifyPassword(post.value,password.value)){error.value='비밀번호가 일치하지 않습니다.';return}if(modal.value==='edit')router.push(`/community/${post.value.id}/edit`);else{deletePost(post.value.id);router.push('/community')}}
const date=v=>new Intl.DateTimeFormat('ko-KR',{dateStyle:'long',timeStyle:'short'}).format(new Date(v))
</script>
<template><main class="page detail"><template v-if="post"><RouterLink class="back" to="/community">← 목록으로</RouterLink><article class="card"><span class="tag">{{post.category}}</span><h1>{{post.title}}</h1><div class="meta">{{date(post.createdAt)}} · 조회 {{post.viewCount}}</div><div class="content">{{post.content}}</div><div class="actions"><button class="btn secondary" @click="modal='edit';password='';error=''">수정</button><button class="btn danger" @click="modal='delete';password='';error=''">삭제</button></div></article></template><div v-else class="empty">게시글을 찾을 수 없습니다.</div><div v-if="modal" class="overlay" @click.self="modal=''" role="dialog"><form class="modal card" @submit.prevent="confirm"><h2>{{modal==='edit'?'수정':'삭제'}} 비밀번호 확인</h2><p>작성할 때 설정한 비밀번호를 입력하세요.</p><input v-model="password" type="password" autofocus><p v-if="error" class="error-box">{{error}}</p><div><button type="button" class="btn secondary" @click="modal=''">취소</button><button class="btn">확인</button></div></form></div></main></template>
<style scoped>.detail{max-width:860px}.back{display:inline-block;color:var(--green);font-weight:800;text-decoration:none;margin-bottom:15px}.detail article{padding:32px}.detail h1{font-size:2rem;margin:15px 0 5px}.meta{color:var(--muted);font-size:.88rem}.content{min-height:240px;padding:30px 0;white-space:pre-wrap;line-height:1.85;border-bottom:1px solid var(--line)}.actions{display:flex;justify-content:flex-end;gap:8px;padding-top:18px}.overlay{position:fixed;inset:0;background:#10231d88;z-index:300;display:grid;place-items:center;padding:18px}.modal{width:min(420px,100%);padding:25px}.modal h2{margin-top:0}.modal input{width:100%;padding:11px;border:1px solid #b8c9c1;border-radius:9px}.modal>div{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}@media(max-width:600px){.detail article{padding:22px}.detail h1{font-size:1.5rem}}</style>
