<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { CATEGORIES, createPost, getPost, updatePost } from '../utils/communityStorage'
const route=useRoute(), router=useRouter(), isEdit=computed(()=>Boolean(route.params.id)), error=ref('')
const form=reactive({title:'',content:'',category:'안전제보',password:''})
onMounted(()=>{if(isEdit.value){const p=getPost(route.params.id);if(!p)return router.replace('/community');Object.assign(form,{title:p.title,content:p.content,category:p.category,password:p.password})}})
function submit(){error.value='';if(form.title.trim().length<2||form.title.trim().length>80)return error.value='제목은 2~80자로 입력해주세요.';if(form.content.trim().length<10||form.content.trim().length>2000)return error.value='내용은 10~2000자로 입력해주세요.';if(form.password.length<4)return error.value='비밀번호는 4자 이상 입력해주세요.';const data={title:form.title.trim(),content:form.content.trim(),category:form.category,password:form.password};const p=isEdit.value?updatePost(route.params.id,data):createPost(data);router.push(`/community/${p.id}`)}
</script>
<template><main class="page editor"><h1 class="page-title">{{isEdit?'게시글 수정':'새 글 작성'}}</h1><p class="page-subtitle">지역 안전에 도움이 되는 정보를 구체적으로 적어주세요.</p><form class="card" @submit.prevent="submit"><div class="field"><label>카테고리</label><select v-model="form.category"><option v-for="c in CATEGORIES" :key="c">{{c}}</option></select></div><div class="field"><label>제목 <small>{{form.title.length}}/80</small></label><input v-model="form.title" maxlength="80" placeholder="제목을 입력하세요"></div><div class="field"><label>내용 <small>{{form.content.length}}/2000</small></label><textarea v-model="form.content" maxlength="2000" rows="12" placeholder="위치, 시간, 상황을 자세히 적어주세요."></textarea></div><div class="field"><label>수정·삭제 비밀번호</label><input v-model="form.password" type="password" minlength="4" placeholder="4자 이상"></div><p v-if="error" class="error-box">{{error}}</p><div class="actions"><button type="button" class="btn secondary" @click="router.back()">취소</button><button class="btn">{{isEdit?'수정 완료':'등록하기'}}</button></div></form></main></template>
<style scoped>.editor{max-width:760px}.editor form{padding:25px;display:grid;gap:20px}.field label{display:flex;justify-content:space-between}.field small{color:var(--muted);font-weight:500}.actions{display:flex;justify-content:flex-end;gap:8px}@media(max-width:600px){.editor form{padding:18px}}</style>
